author/urls.py
from django.conf.urls import url
from . import views

app_name = 'author'

urlpatterns = [
     
     url(r'^addauthor$', views.add_author ,name="author"),
     url(r'^(?P<id>\d+)/author$', views.author_details ,name='author_details'),
     url(r'^authors$', views.all_authors ,name="all_author"),
     url(r'^(?P<id>\d+)/books$', views.all_author_books ,name="all_author_books"),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
     
     url(r'^$', views.all_books ,name="all_books"),
     url(r'^add$', views.add_book ,name='add_book'),
     url(r'^(?P<id>\d+)$', views.get_book ,name='book'),
     url(r'^(?P<id>\d+)/edit$', views.edit_book ,name='edit_book'),
    url(r'^admin$', views.admin ,name='admin'),    
     url(r'^(?P<id>\d+)/delete$', views.delete_book ,name='delete_book'),
     url(r'^$', views.home ,name='home'),


]

library/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls',namespace='env')),
    path ('',include('author.urls',namespace='env1'))
    ] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

author/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=50)
    mail = models.EmailField()
    desc = models.TextField(default='')
    img = models.ImageField(upload_to='author_image/',default='author_image/default.png')

    def __str__(self):
        return self.name

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from author.models import Author

# Create your models here.


class Book(models.Model):
    Published = 'PB'
    Withdrawn = 'WD'
    Draft = 'DF'

    author = models.ForeignKey(Author,on_delete=models.CASCADE,related_name="author_book")
    title = models.CharField(max_length=50)
    desc = models.TextField(default='')
    img = models.ImageField(upload_to='book_image/',default='book_image/default.png')
    state_choices = [
        (Published,'Published'),
        (Withdrawn,'Withdrawn'),
        (Draft,'Draft')
    ]
    state = models.CharField(max_length=2,choices=state_choices,default= '')
    created_date = models.DateTimeField(default=timezone.now)


    def is_upperclass(self):
        return self.state 
    
    
    
    def __str__(self):
        return self.title


    

author/forms.py
from django import forms
from . import models
from .models import Author


class authorform (forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name','mail','desc','img']

books/forms.py
from django import forms
from . import models
from .models import Book


class bookform (forms.ModelForm):
    class Meta:
        model = Book
        fields = ['author','title','desc','img','state']

author/views.py
from django.shortcuts import render ,get_object_or_404 , redirect
from .models import Author
from .forms import authorform
from django.http import HttpResponse
from books.models import Book
from books import views

# Create your views here.



def add_author(request):
        if request.method =='POST':
            form = authorform(request.POST)
            if form.is_valid():
                new_form =form.save(commit= False)
                new_form.user=request.user
                new_form.save()
                return redirect('/')


        else :
            form = authorform()


        context = {
            'form': form
        }

        return render(request,'author.html',context) 

def author_details (request,id):
    current_author = get_object_or_404(Author,id=id)

    context = {'author': current_author }
    return render( request,'author_details.html',context)
    



def all_authors(request):
    all_authors = Author.objects.all()
    
    context = {
        'all_authors' : all_authors
    }
    return render(request, 'all_author.html',context)


def all_author_books(request,id):
    all_author_books =Book.objects.filter(author__id=id)
    context = {
        'all_author_books' : all_author_books
    }
    return render(request, 'all_author_books.html',context)

books/views.py
from django.shortcuts import render ,get_object_or_404 , redirect

from books.models import Book
from .forms import bookform
# Create your views here.

def all_books(request):
    all_books = Book.objects.all()

    context = {
        'all_books' : all_books
    }
    return render(request, 'all_books.html',context)




def add_book(request):
        if request.method =='POST':
            form = bookform(request.POST)
            if form.is_valid():
                new_form =form.save(commit= False)
                new_form.user=request.user
                new_form.save()
                return redirect('/')


        else :
            form = bookform()


        context = {
            'form': form
        }

        return render(request,'add_book.html',context) 



def get_book(request,id):
    # current_post = post.objects.get(id = id)
    current_book = get_object_or_404(Book,id=id)

    context = {
        'book': current_book 
    }
    return render( request,'detail.html',context)





def edit_book(request,id):
    cur_book = get_object_or_404(Book,id=id)
    if request.method =='POST':
        form = bookform(request.POST, instance=cur_book )
        if form.is_valid():
            new_form =form.save(commit= False)
            new_form.user=request.user
            new_form.save()
            return redirect('/')

    else :
        form = bookform(instance=cur_book)


    context = {
        'form': form
    }

    return render(request,'edit_book.html',context) 

def admin(request):
    return redirect('admin')




def delete_book(request,id):
    cr_book = get_object_or_404(Book,id=id)
    cr_book.delete()
    return redirect("/")



def home(request):
    return redirect("/")

author/templates/all_author.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Main Page</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">AUTHORS</a>
        <form class="form-inline">
        <a href="{% url 'env:admin' %}"
        type="button" class=" btn btn-link form-control ">admin </a>
        <a href="{% url 'env:home' %}" 
        type=" button " class=" btn btn-link form-control ">Home </a>
        <a  href="{% url 'env:add_book' %}" 
        type="button" class=" btn btn-link form-control ">add book</a>
        <a href="{% url 'env1:author' %}"
        type="button" class=" btn btn-link form-control ">add author</a>
        <a href="{% url 'env1:all_author' %}"
        type="button" class=" btn btn-link form-control ">view author</a>
        </form>
    </nav>
    
    <div class="row">
        {% for author in all_authors %}
        <div class="col-4 mt-4">
          <div class="card">
              {% if author.img %}
            <img src="{{author.img.url}}" class="card-img-top" alt="..." height="300" width="100" >
             {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{author.name}}</h5>
              <p class="card-text">{{author.desc}}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'env1:author_details' author.id %}" class="btn btn-info">author's details</a>
            </div>
          </div>
        </div>
        {% endfor %}   
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <hr>
<button> <a href="{% url 'env:add_book' %}"> add book </a></button>
<button><a href="{% url 'env:admin' %}"> admin </a></button>
<button><a href="{% url 'env1:author' %}"> add author </a></button>

  </body>
</html>

author/templates/all_author_books.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Main Page</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">BOOKS</a>
        <form class="form-inline">
        <a href="{% url 'env:home' %}" 
        type=" button " class=" btn btn-link form-control ">Home </a>
        <a href="{% url 'env:admin' %}"
        type="button" class=" btn btn-link form-control ">admin </a>
        
        </form>
    </nav>
    
    <div class="row">
        {% for book in all_author_books %}
        <div class="col-4 mt-4">
          <div class="card">
              {% if book.img %}
            <img src="{{book.img.url}}" class="card-img-top" alt="..." height="300" width="100" >
             {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{book.title}}</h5>
              <p class="card-text">{{book.desc}}</p>
            </div>
            
          </div>
        </div>
        {% endfor %}   
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <hr>

  </body>
</html>

author/templates/author.html
<h1>helo author</h1>

<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}

{{form}}

<button type="submit" class="btn btn-primary">add author</button>

</form>

author/templates/author_details.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Main Page</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">author's details</a>
        <form class="form-inline">
        <a href="{% url 'env1:all_author_books' author.id %}"
        type=" button " class=" btn btn-link form-control ">author's books </a>
        <a href="{% url 'env:home' %}" 
        type=" button " class=" btn btn-link form-control ">Home </a>
        <a href="{% url 'env:admin' %}"
        type="button" class=" btn btn-link form-control ">admin </a>
        
        </form>
    </nav>
    
    <div class="row">
        
        <div class="col-4 mt-4">
          <div class="card">
              {% if author.img %}
            <img src="{{author.img.url}}" class="card-img-top" alt="..." height="300" width="100" >
             {% endif %}
            <div class="card-body">
              <h5 class="card-title">>{{author.name}}</h5>
              <p class="card-text">{{author.desc}}</p>
            </div>
            
          </div>
        </div>
           
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <hr>

  </body>
</html>

books/templates/add_book.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}

{{form}}

<button type="submit" class="btn btn-primary">add new book</button>

</form>

books/templates/all_books.html
{% load static %}

{% comment %}
<hr>

{% for book in all_books %}
    <h3><a href="{% url 'env:book' book.id %}" >
        {{book.title}} </a></h3>
{% endfor %}
<hr>
<button> <a href="{% url 'env:add_book' %}"> add book </a></button>
<button><a href="{% url 'env:admin' %}"> admin </a></button>
<button><a href="{% url 'env1:author' %}"> add author </a></button>
{% endcomment %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Main Page</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">LIBRARY</a>
        <form class="form-inline">
        <a href="{% url 'env:admin' %}"
        type="button" class=" btn btn-link form-control ">admin </a>
        <a  href="{% url 'env:add_book' %}" 
        type="button" class=" btn btn-link form-control ">add book</a>
        <a href="{% url 'env1:author' %}"
        type="button" class=" btn btn-link form-control ">add author</a>
        <a href="{% url 'env1:all_author' %}"
        type="button" class=" btn btn-link form-control ">view authors</a>
        </form>
    </nav>
    
    <div class="row">
        {% for book in all_books %}
        <div class="col-4 mt-4">
          <div class="card">
              {% if book.img %}
            <img src="{{book.img.url}}" class="card-img-top" alt="..." height="300" width="100" >
             {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{book.title}}</h5>
              <p class="card-text">{{book.desc}}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'env:book' book.id %}" class="btn btn-info">View details</a>
            </div>
          </div>
        </div>
        {% endfor %}   
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <hr>
<button> <a href="{% url 'env:add_book' %}"> add book </a></button>
<button><a href="{% url 'env:admin' %}"> admin </a></button>
<button><a href="{% url 'env1:author' %}"> add author </a></button>

  </body>
</html>

books/templates/detail.html
{% comment %}
<h1>{{book}}</h1>
<br>
<h1>{{book.desc}}</h1>
<hr>
<button><a href="{% url 'env:edit_book' book.id %}">edit book</a></button>
<button><a href="{% url 'env:delete_book' book.id %}">delete book</a></button>
{% endcomment %}

{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Main Page</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">details</a>
        <form class="form-inline">
        <a href="{% url 'env:home' %}" 
        type=" button " class=" btn btn-link form-control ">Home </a>
        <a href="file:///G:/ITI/Client%20Side%20Technologies/BootStrap/lab1/registrationPage.html" 
        type="button" class=" btn btn-link form-control ">SignUP</a>
        </form>
    </nav>
    <h1>welcome</h1>
    <div class="row">
        
        <div class="col-4 mt-4">
          <div class="card">
              {% if book.img %}
            <img src="{{book.img.url}}" class="card-img-top" alt="..." height="300" width="100" >
             {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{book.title}}</h5>
              <p class="card-text">description:{{book.desc}}</p>
              <p class="card-text">state:{{book.state}}</p>
              <p class="card-text"> author:{{book.author.name}}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'env1:author_details' book.author.id %}" class="btn btn-info">author details</a>
            </div>
          </div>
        </div>
         
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <hr>
    <hr>
    <button><a href="{% url 'env:edit_book' book.id %}">edit book</a></button>
    <button><a href="{% url 'env:delete_book' book.id %}">delete book</a></button>


  </body>
</html>

books/templates/edit_book.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}

{{form}}

<button  type="submit" class="btn btn-primary">save book</button>

</form>